system: true

BLAZE_POWDER:
  - 0

FERMENTED_SPIDER_EYE:
  - 0

GHAST_TEAR:
  - 0

GLISTERING_MELON_SLICE:
  - 0

GOLDEN_CARROT:
  - 0

GUNPOWDER:
  - 0

MAGMA_CREAM:
  - 0

NETHER_WART:
  - 0

PHANTOM_MEMBRANE:
  - 0

PUFFERFISH:
  - 0

RABBIT_FOOT:
  - 0

SPIDER_EYE:
  - 0

SUGAR:
  - 0

TURTLE_HELMET:
  - 0
